"""
End-to-end test: create a doc with new template structure,
inject AI summary and verify ordering matches Teams UI.
"""
from pathlib import Path
from docx import Document

# 1) Create doc with new template structure
print("=" * 70)
print("1) Creating doc with new template structure")
print("=" * 70)
test_doc_path = "runs/2026-03-02__onenote-org/tmp/e2e_test_new_template.docx"
doc = Document()
doc.add_heading("SC Internal Deal Desk Project Meeting", level=1)
doc.add_paragraph("Meeting Time: 2026-03-10 13:00 - 14:00")
doc.add_paragraph("Organizer: Chrystal, Danielle")
doc.add_heading("Attendees", level=2)
doc.add_paragraph("• Chrystal, Danielle (none)")
doc.add_heading("Description", level=2)
doc.add_paragraph("Meeting description here")

doc.add_heading("Manual Notes", level=1)
doc.add_paragraph("\n")

doc.add_heading("Teams AI Summary", level=1)
doc.add_paragraph("\n")

doc.add_heading("Teams Custom Summary (Loss-Less Extraction)", level=1)
doc.add_paragraph("\n")

doc.add_heading("Otter Transcript Imports (Append-Only)", level=1)
doc.add_paragraph("Otter transcripts will be appended below.\n")

doc.save(test_doc_path)
print(f"Created: {test_doc_path}")

# Show structure
for i, p in enumerate(doc.paragraphs):
    if p.style.name.startswith('Heading') or p.text.strip():
        print(f"  {i:3d} [{p.style.name:15s}] {p.text[:60]}")

# 2) Inject AI summary
print("\n" + "=" * 70)
print("2) Injecting AI summary from saved HTML")
print("=" * 70)
import subprocess, sys
result = subprocess.run(
    [sys.executable,
     "runs/2026-03-02__onenote-org/scripts/inject_ai_summary_rich.py",
     test_doc_path,
     "--from-file", "runs/2026-03-02__onenote-org/tmp/deal_desk_ai_summary.html"],
    capture_output=True, text=True
)
print(result.stdout.strip())
if result.stderr:
    print("STDERR:", result.stderr)

# 3) Inject custom summary
print("\n" + "=" * 70)
print("3) Injecting Custom Summary")
print("=" * 70)
# Create a small test custom summary
cs_path = Path("runs/2026-03-02__onenote-org/tmp/test_custom_summary.txt")
cs_path.write_text("### Exhaustive Topic Extraction\n\n- **Deal Desk Build-Out**: Phased approach\n- **Growth Project**: Heat map analysis\n- **Contract Standards**: Exception-based review\n\n### Action Items\n- Follow up with Kyle MacKinnon\n- Review value assurance scorecard\n")
result2 = subprocess.run(
    [sys.executable,
     "runs/2026-03-02__onenote-org/scripts/inject_teams_recap.py",
     "--doc", test_doc_path,
     "--custom-summary", str(cs_path)],
    capture_output=True, text=True
)
print(result2.stdout.strip())
if result2.stderr:
    print("STDERR:", result2.stderr)

# 4) Verify final doc structure
print("\n" + "=" * 70)
print("4) Final document structure")
print("=" * 70)
doc = Document(test_doc_path)
for i, p in enumerate(doc.paragraphs):
    style = p.style.name
    text = p.text[:90] if p.text else ""
    drawings = p._element.findall(
        './/{http://schemas.openxmlformats.org/wordprocessingml/2006/main}drawing'
    )
    if drawings:
        print(f"  {i:3d} [{style:15s}] [IMAGE x{len(drawings)}]")
    elif style.startswith('Heading') or text.strip():
        print(f"  {i:3d} [{style:15s}] {text}")
print("=" * 70)

# 5) Verify order matches expected Teams UI order
print("\n" + "=" * 70)
print("5) ORDER VERIFICATION")
print("=" * 70)
expected_topic_order = [
    "Deal Desk Build-Out",
    "Growth Project",
    "Defining Success",
    "Scenario Modeling",
    "Establishing Contract Review",
    "Action Items and Next Steps",
    "Guiding Principles",
    "Follow-up tasks",
]

# Find text paragraphs in the AI Summary section
ai_start = None
ai_end = None
for i, p in enumerate(doc.paragraphs):
    if p.style.name.startswith('Heading') and "Teams AI Summary" in p.text:
        ai_start = i + 1
    elif ai_start and p.style.name.startswith('Heading') and int(p.style.name.split()[-1]) <= 1:
        ai_end = i
        break

if ai_start and ai_end:
    doc_topics = []
    for i in range(ai_start, ai_end):
        text = doc.paragraphs[i].text[:50]
        if text.strip():
            doc_topics.append(text)
    
    print("Topics found in doc (first 50 chars each):")
    for t in doc_topics:
        print(f"  - {t}")
    
    # Check first topic appears in expected order
    first_topic = doc_topics[0] if doc_topics else ""
    if "Generated by AI" in first_topic or "Deal Desk Build-Out" in first_topic:
        print("\n✅ ORDER CORRECT: Content starts with first topic (or AI disclaimer)")
    else:
        print(f"\n❌ ORDER WRONG: Content starts with '{first_topic}' instead of 'Deal Desk Build-Out'")
else:
    print("Could not find AI Summary section boundaries")
