"""
Test script: Parse the Deal Desk AI summary HTML, create a blank Word doc,
inject the content, and print a comparison manifest showing the expected
order of text blocks and images.
"""
import base64
import io
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup, NavigableString, Tag
from docx import Document
from docx.shared import Inches


def parse_html_to_ordered_blocks(html: str):
    """
    Walk the HTML tree in document order. Produce a flat list of blocks
    preserving the exact order: text, images, section headers.
    
    The Teams AI summary HTML structure is:
      <div>Generated by AI...</div>
      <div>Meeting notes:</div>
      <ul>
        <li><b>Topic Title: </b>Topic summary text
          <ul>
            <li><b>Sub-topic: </b>Sub-topic text</li>
            ...
            <li><img .../><img .../></li>   <-- images at end of topic
          </ul>
        </li>
        ...
      </ul>
      <div>Follow-up tasks:</div>
      <ul>
        <li><b>Task title: </b>Task description</li>
        ...
      </ul>
    """
    soup = BeautifulSoup(html, 'html.parser')
    blocks = []
    
    def walk(element, depth=0):
        for child in element.children:
            if isinstance(child, NavigableString):
                text = child.strip()
                if text:
                    is_bold = child.parent and child.parent.name in ('b', 'strong')
                    blocks.append({
                        "type": "text",
                        "text": text,
                        "bold": is_bold,
                        "depth": depth,
                    })
            elif isinstance(child, Tag):
                if child.name == 'img':
                    src = child.get('src', '')
                    alt = child.get('alt', '')
                    m = re.match(r'data:image/([\w+]+);base64,(.+)', src, re.DOTALL)
                    if m:
                        ext = m.group(1).replace('jpeg', 'jpg')
                        img_bytes = base64.b64decode(m.group(2))
                        blocks.append({
                            "type": "image",
                            "data": img_bytes,
                            "ext": ext,
                            "alt": alt,
                        })
                elif child.name == 'br':
                    pass
                elif child.name in ('ul', 'ol'):
                    walk(child, depth + 1)
                elif child.name == 'li':
                    walk(child, depth)
                else:
                    walk(child, depth)
    
    walk(soup)
    return blocks


def merge_adjacent_text(blocks):
    """
    Merge consecutive text blocks at the same depth into single entries
    with multiple runs (preserving bold/non-bold).
    """
    merged = []
    for b in blocks:
        if b["type"] == "text":
            if (merged
                    and merged[-1]["type"] == "text"
                    and merged[-1]["depth"] == b["depth"]):
                merged[-1].setdefault("runs", [])
                if not merged[-1]["runs"]:
                    merged[-1]["runs"] = [{"text": merged[-1]["text"], "bold": merged[-1]["bold"]}]
                merged[-1]["runs"].append({"text": b["text"], "bold": b["bold"]})
                merged[-1]["text"] += " " + b["text"]
            else:
                merged.append(dict(b))
        else:
            merged.append(b)
    return merged


def create_test_doc(blocks, output_path):
    """Create a blank Word doc and inject blocks in order."""
    doc = Document()
    doc.add_heading("AI Summary (Test Injection)", level=1)
    
    for i, block in enumerate(blocks):
        if block["type"] == "text":
            p = doc.add_paragraph()
            p.clear()
            if block.get("runs"):
                for run_info in block["runs"]:
                    run = p.add_run(run_info["text"] + " ")
                    run.bold = run_info["bold"]
            else:
                run = p.add_run(block["text"])
                run.bold = block.get("bold", False)
        elif block["type"] == "image":
            p = doc.add_paragraph()
            run = p.add_run()
            run.add_picture(io.BytesIO(block["data"]), width=Inches(5.5))
    
    doc.save(output_path)
    return doc


def print_manifest(blocks):
    """Print a numbered manifest of all blocks in order."""
    print("=" * 80)
    print("CONTENT MANIFEST (in order as parsed from HTML)")
    print("=" * 80)
    for i, b in enumerate(blocks):
        if b["type"] == "text":
            depth = b.get("depth", 0)
            prefix = "  " * depth
            bold_marker = "[BOLD] " if b.get("bold") else ""
            text_preview = b["text"][:100]
            print(f"  {i:3d}  {prefix}TEXT {bold_marker}{text_preview}")
        elif b["type"] == "image":
            alt = b.get("alt", "")
            size_kb = len(b["data"]) / 1024
            print(f"  {i:3d}  IMAGE  alt='{alt}'  size={size_kb:.0f}KB")
    print("=" * 80)
    print(f"Total: {sum(1 for b in blocks if b['type']=='text')} text, "
          f"{sum(1 for b in blocks if b['type']=='image')} images")


def verify_doc_order(doc_path):
    """Read back the created doc and print its paragraph order."""
    doc = Document(doc_path)
    print("\n" + "=" * 80)
    print("DOCUMENT CONTENT (as read back from .docx)")
    print("=" * 80)
    for i, p in enumerate(doc.paragraphs):
        style = p.style.name
        text = p.text[:100] if p.text else ""
        # Check for images
        drawings = p._element.findall(
            './/{http://schemas.openxmlformats.org/wordprocessingml/2006/main}drawing'
        )
        if drawings:
            print(f"  {i:3d}  [{style:15s}]  [IMAGE x{len(drawings)}]")
        elif text:
            print(f"  {i:3d}  [{style:15s}]  {text}")
    print("=" * 80)


def main():
    html_file = "runs/2026-03-02__onenote-org/tmp/deal_desk_ai_summary.html"
    output_path = "runs/2026-03-02__onenote-org/tmp/test_deal_desk_injection.docx"
    
    html = Path(html_file).read_text(encoding='utf-8')
    print(f"Read HTML: {len(html)} chars")
    
    # Parse
    raw_blocks = parse_html_to_ordered_blocks(html)
    print(f"Raw blocks: {len(raw_blocks)}")
    
    # Print raw manifest (before merging)
    print_manifest(raw_blocks)
    
    # Merge adjacent text
    merged_blocks = merge_adjacent_text(raw_blocks)
    print(f"\nAfter merging: {len(merged_blocks)} blocks")
    print_manifest(merged_blocks)
    
    # Create test doc
    create_test_doc(merged_blocks, output_path)
    print(f"\nCreated test doc: {output_path}")
    
    # Read back and verify
    verify_doc_order(output_path)


if __name__ == "__main__":
    main()
