from docx import Document

files = {
    "Platform Showcase": "/Users/matt_bossemeyer/Library/CloudStorage/OneDrive-Premier,Inc/Notetaking/Meeting Notes/2026/03/10/2026-03-10 0930 - Platform Showcase - Zach-Elise-Jesse - eid1f0145bc.docx",
    "SC Deal Desk": "/Users/matt_bossemeyer/Library/CloudStorage/OneDrive-Premier,Inc/Notetaking/Meeting Notes/2026/03/10/2026-03-10 1300 - SC Internal Deal Desk Project Meeting - Danielle-Bill-Matthew - eid9d3d92a8.docx",
}

for name, path in files.items():
    doc = Document(path)
    print(f"\n=== {name} ===")
    has_ai = False
    has_custom = False
    for i, p in enumerate(doc.paragraphs):
        if p.style.name.startswith("Heading"):
            print(f"  [{i}] {p.style.name}: {p.text[:100]}")
        if "Generated by AI" in p.text or "Meeting notes:" in p.text:
            has_ai = True
        if "EXHAUSTIVE TOPIC EXTRACTION" in p.text:
            has_custom = True
    print(f"  Has AI Summary content: {has_ai}")
    print(f"  Has Custom Summary content: {has_custom}")
    print(f"  Total paragraphs: {len(doc.paragraphs)}")
