from pptx import Presentation
from pptx.util import Inches, Pt
import sys
import os

# Configuration
RUN_ID = "2026-01-06__accelerating_technology_delivery_presentation"
OUTPUT_DIR = f"runs/{RUN_ID}/exports"
OUTPUT_FILE = f"{OUTPUT_DIR}/draft_v1_branded.pptx"
# Using the fixed/converted template 
MASTER_TEMPLATE = f"runs/{RUN_ID}/tmp/Premier_Template_Fixed.pptx"

def create_presentation():
    # 1. Create presentation object from Master Template
    if not os.path.exists(MASTER_TEMPLATE):
        print(f"Error: Template not found at {MASTER_TEMPLATE}")
        return

    prs = Presentation(MASTER_TEMPLATE)

    # 2. Add Title Slide
    # Layout 1: "Premier Title Slide 1 - Dark"
    # Placeholder idx=0, type=TITLE
    # Placeholder idx=10, type=BODY (Subtitle)
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.placeholders[0]
    subtitle = slide.placeholders[10]

    title.text = "Accelerating Technology Delivery"
    subtitle.text = "Generated by Computer Use Agent (Branded)"

    # 3. Add Content Slide
    # Layout 4: "Premier Main Content 1a"
    # Placeholder idx=0, type=TITLE
    # Placeholder idx=10, type=OBJECT (Content)
    bullet_slide_layout = prs.slide_layouts[4]
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes

    title_shape = shapes.placeholders[0]
    body_shape = shapes.placeholders[10]
    
    title_shape.text = "Agenda"
    tf = body_shape.text_frame
    tf.text = "Overview of current delivery velocity"

    p = tf.add_paragraph()
    p.text = "Bottlenecks identified in Q4"
    p.level = 1

    p = tf.add_paragraph()
    p.text = "Proposed automation solutions"
    p.level = 1

    # 4. Save
    print(f"Saving presentation to {OUTPUT_FILE}...")
    # Ensure output directory exists (redundant safety check)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    prs.save(OUTPUT_FILE)
    print("Done.")

if __name__ == "__main__":
    create_presentation()
