import copy
import os
import sys
from pptx import Presentation

# Configuration
RUN_ID = "2026-01-06__accelerating_technology_delivery_presentation"
COMPONENT_LIBRARY = f"runs/{RUN_ID}/assets/Premier_Components.pptx"
OUTPUT_FILE = f"runs/{RUN_ID}/exports/draft_v2_components.pptx"

def duplicate_slide(prs, index):
    """
    Duplicates the slide at the specified index in the presentation.
    Adds the new slide to the end of the presentation.
    
    This is a "poor man's clone" that works reliably for text-based layouts
    by adding a new slide with the same layout and copying shape text.
    
    For a true low-level XML clone, we'd need more complex lxml manipulation.
    For this MVP (Consensus Plan), we will instantiate a NEW slide of the 
    SAME layout, which effectively "clones" the component structure, 
    then we populate it.
    """
    source_slide = prs.slides[index]
    layout = source_slide.slide_layout
    new_slide = prs.slides.add_slide(layout)
    
    # In a full "Clone", we would copy shapes.
    # But since our Components are just Layouts + Placeholders,
    # instantiating the layout IS the clone.
    # The "Component Library" concept effectively maps "Logical Component" -> "Layout Index".
    return new_slide

def generate_presentation_v2():
    if not os.path.exists(COMPONENT_LIBRARY):
        print("Error: Component Library not found.")
        return

    # Load the Library - this IS our base presentation now
    prs = Presentation(COMPONENT_LIBRARY)
    
    # Map our "Component Prototypes" (which are currently AT THE END of the deck)
    # We appended Title, List, Section.
    # So:
    # -3: Title Component
    # -2: List Component
    # -1: Section Component
    
    # --- PROTOTYPE MAP --
    PROTO_TITLE = prs.slides[-3].slide_layout
    PROTO_LIST = prs.slides[-2].slide_layout
    PROTO_SECTION = prs.slides[-1].slide_layout 
    
    print("Generating presentation using Component Library...")

    # 1. Slide 1: Title
    slide = prs.slides.add_slide(PROTO_TITLE)
    slide.placeholders[0].text = "Accelerating Technology Delivery"
    slide.placeholders[10].text = "Generated by Computer Use Agent (V2 - Component Mode)"

    # 2. Slide 2: Agenda
    slide = prs.slides.add_slide(PROTO_LIST)
    slide.placeholders[0].text = "Agenda"
    slide.placeholders[10].text = "1. Current Velocity\n2. The Bottleneck Analysis\n3. Proposed Solution\n4. Roadmap Q1-Q2"

    # 3. Slide 3: Section Header
    slide = prs.slides.add_slide(PROTO_SECTION)
    try:
        slide.placeholders[0].text = "Phase 1: Analysis"
    except:
        pass # Layout 2 might vary

    # 4. Slide 4: Content
    slide = prs.slides.add_slide(PROTO_LIST)
    slide.placeholders[0].text = "Bottlenecks Identified"
    slide.placeholders[10].text = "• Manual code reviews delay merge by 48h\n• Integration tests are flaky (20% failure rate)\n• Deployment pipeline is monolithic"
    
    # --- CLEANUP ---
    # We skip deleting slides to ensure file integrity.
    # The output deck will contain the Library/Template slides + the New Content.
    # User should look at the end of the deck.

    # Save
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    prs.save(OUTPUT_FILE)
    print(f"Draft V2 generated at {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_presentation_v2()
